name: iOS CI

on:
  push:
    branches: [ develop, release ]
  pull_request:

jobs:
  lint:
    runs-on: macos-latest
        steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        run: ./.github/prepare-workflow
      - name: Run lint
        run: swiftlint --reporter "emoji"
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        run: ./.github/prepare-workflow
      - name: Build
        run: xcodebuild build -scheme Habitica
  unit-tests:
    runs-on: macos-latest
    strategy:
      matrix:
        destination:
          - "platform=iOS Simulator,name=iPhone 8,OS=13.7"
          - "platform=iOS Simulator,name=iPhone 11,OS=14.5"
          - "platform=iOS Simulator,name=iPhone 12,OS=15.2"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        run: ./.github/prepare-workflow
      - name: Build
        run: xcodebuild clean test -scheme 'Habitica' -destination '${{ matrix.destination }}' -testPlan "Unit Tests" -showBuildTimingSummary
  ui-tests:
    runs-on: macos-latest
    strategy:
      matrix:
        destination:
          - "platform=iOS Simulator,name=iPhone 8,OS=13.7"
          - "platform=iOS Simulator,name=iPhone 11,OS=14.5"
          - "platform=iOS Simulator,name=iPhone 12,OS=15.2"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        run: ./.github/prepare-workflow
      - name: Build
        run: xcodebuild clean test -scheme 'Habitica' -destination '${{ matrix.destination }}' -testPlan "UI Tests" -showBuildTimingSummary